project_id = "esbqtuljvejvrzawsqgk"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.get-registration-public]
verify_jwt = false

[functions.create-staff]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.cleanup-expired-registrations]
verify_jwt = false